name: CI Serenity BDD - API Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test-apis:
    runs-on: ubuntu-latest

    # 🔹 Variables de entorno globales (para todo el job)
    env:
      BASE_URL: https://opensource-demo.orangehrmlive.com/web/index.php
      URL: /api/v2/pim/employees
      URL_TOKEN: https://opensource-demo.orangehrmlive.com
      URL_TOKENS: /web/index.php/auth/validate
      USERNAME: Admin
      PASSWORD: admin123

    steps:
      # 1️⃣ Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ Dar permisos al Gradle Wrapper
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
        working-directory: AUTOMATIZACION_APIS

      # 4️⃣ Compilar el proyecto
      - name: Build API Automation Project
        run: ./gradlew clean build -x test
        working-directory: AUTOMATIZACION_APIS

      - name: Verify test resource paths
        run: | 
          echo "📂 Verificando recursos..."
          find src/test/resources -type f
          echo "📂 Verificando recursos compilados..."./gradlew processTestResources
          find build/resources/test -type f || echo "⚠️ No se encontraron recursos compilados"
        working-directory: AUTOMATIZACION_APIS

      # 6️⃣ Ejecutar las pruebas Serenity con variables de entorno
      - name: Run Serenity API Tests
        continue-on-error: true
        run: |
          ./gradlew test aggregate \-Dbase_url=${{ env.BASE_URL }} \-Durl=${{ env.URL }} \-Durl_token=${{ env.URL_TOKEN }} \-Durl_tokens=${{ env.URL_TOKENS }} \-Dusername=${{ env.USERNAME }} \-Dpassword=${{ env.PASSWORD }}
        working-directory: AUTOMATIZACION_APIS


      # 7️⃣ Subir reporte Serenity
      - name: Upload Serenity API Reports
        uses: actions/upload-artifact@v4
        with:
          name: serenity-api-report
          path: AUTOMATIZACION_APIS/target/site/serenity/
