name: CI Serenity BDD - API Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test-apis:
    runs-on: ubuntu-latest

    # 🔹 Variables de entorno globales (para todo el job)
    env:
      base_url: https://opensource-demo.orangehrmlive.com/web/index.php
      url: /api/v2/pim/employees
      url_token: https://opensource-demo.orangehrmlive.com
      url_tokens: /web/index.php/auth/validate
      username: Admin
      password: admin123

    steps:
      # 1️⃣ Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ Dar permisos al Gradle Wrapper
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
        working-directory: AUTOMATIZACION_APIS

      # 4️⃣ Compilar el proyecto
      - name: Build API Automation Project
        run: ./gradlew clean build -x test
        working-directory: AUTOMATIZACION_APIS

      # 5️⃣ Verificar recursos
      - name: List test resources
        run: ls -R src/test/resources
        working-directory: AUTOMATIZACION_APIS

      # 6️⃣ Ejecutar las pruebas Serenity con variables de entorno
      - name: Run Serenity API Tests
        run: |
          ./gradlew test aggregate \
            -Dbase_url=${{ env.BASE_URL }} \
            -Durl=${{ env.URL }} \
            -Durl_token=${{ env.URL_TOKEN }} \
            -Durl_tokens=${{ env.URL_TOKENS }} \
            -Dusername=${{ env.USERNAME }} \
            -Dpassword=${{ env.PASSWORD }}
        working-directory: AUTOMATIZACION_APIS

      # 7️⃣ Subir reporte Serenity
      - name: Upload Serenity API Reports
        uses: actions/upload-artifact@v4
        with:
          name: serenity-api-report
          path: AUTOMATIZACION_APIS/target/site/serenity/
